# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-31 06:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170531_0611'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserModel',
            new_name='UserProfile',
        ),
    ]
