# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-31 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
