# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-31 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20170531_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(blank=True, default='', unique=True),
        ),
    ]
